account/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy
from .views import login_view, account_view, register_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', account_view, name='home'),

    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        success_url=reverse_lazy('account:password_change_done')), name='password_change'),

    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),

    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

courses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<int:pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<int:pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<int:pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),

    path('module/<int:module_id>/content/<str:model_name>/create/', views.ContentCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/content/<str:model_name>/<int:id>/', views.ContentCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),

    path('module/order/', views.ModuleOrderView.as_view(), name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
]

educa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import index

urlpatterns = [
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('', index, name='index'),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <title>{% if html_title %} {{ html_title }} {% else %} {% block html_title %} {% endblock %} {% endif %}</title>

    <!--    styles-->
    <link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!--    <link href="https://fonts.googleapis.com/css?family=Kanit&display=swap" rel="stylesheet">-->
    <!--    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">-->


    <!--    scripts-->
    <script src="{% static 'jquery/jquery-3.3.1.slim.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'jquery/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'jquery/jquery-ui.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'ajax/popper.min.js' %}" type="text/javascript"></script>
    <script>
    // ---------Responsive-navbar-active-animation-----------
function test(){
  var tabsNewAnim = $('#navbarSupportedContent');
  var selectorNewAnim = $('#navbarSupportedContent').find('li').length;
  var activeItemNewAnim = tabsNewAnim.find('.active');
  var activeWidthNewAnimHeight = activeItemNewAnim.innerHeight();
  var activeWidthNewAnimWidth = activeItemNewAnim.innerWidth();
  var itemPosNewAnimTop = activeItemNewAnim.position();
  var itemPosNewAnimLeft = activeItemNewAnim.position();
  $(".hori-selector").css({
    "top":itemPosNewAnimTop.top + "px",
    "left":itemPosNewAnimLeft.left + "px",
    "height": activeWidthNewAnimHeight + "px",
    "width": activeWidthNewAnimWidth + "px"
  });
  $("#navbarSupportedContent").on("click","li",function(e){
    $('#navbarSupportedContent ul li').removeClass("active");
    $(this).addClass('active');
    var activeWidthNewAnimHeight = $(this).innerHeight();
    var activeWidthNewAnimWidth = $(this).innerWidth();
    var itemPosNewAnimTop = $(this).position();
    var itemPosNewAnimLeft = $(this).position();
    $(".hori-selector").css({
      "top":itemPosNewAnimTop.top + "px",
      "left":itemPosNewAnimLeft.left + "px",
      "height": activeWidthNewAnimHeight + "px",
      "width": activeWidthNewAnimWidth + "px"
    });
  });
}
$(document).ready(function(){
  setTimeout(function(){ test(); });
});
$(window).on('resize', function(){
  setTimeout(function(){ test(); }, 500);
});
$(".navbar-toggler").click(function(){
  setTimeout(function(){ test(); });
});
</script>

    {% block extra_style %}
    {% endblock %}
</head>

<body>
{% block html_body_content %}
{% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block html_body_content %}
{%include 'navbar.html' %}
{% endblock %}

templates/navbar.html
{% load static %}

<header>
    <nav class="navbar navbar-expand-lg navbar-mainbg">
    <a class="navbar-brand navbar-logo" href="/"><small><strong>EDUCA ACADEMY</strong></small></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                {% if not request.user.is_authenticated %}

                <li class="nav-item {% if page_name == 'home' %}active{%endif%}">
                    <a class="nav-link" href="/"><i class="far fa-address-book"></i>Welcome</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#one"><i class="far fa-clone"></i>About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Contact</a>
                </li>
                <li class="nav-item {% if page_name == 'account' %}active{%endif%}">
                    <a class="nav-link" href="{% url 'account:home' %}"><i class="far fa-chart-bar"></i>My Account</a>
                </li>
                {% else %}

                <li class="nav-item {% if page_name == 'account' %}active{%endif%}">
                    <a class="nav-link text-white" href="{% url 'courses:manage_course_list' %}"><i class="far fa-chart-bar"></i>My Courses</a>
                </li>
                <li class="nav-item {% if page_name == 'account' %}active{%endif%}">
                    <a class="nav-link text-white" href="{% url 'account:logout' %}"><i class="far fa-chart-bar"></i>Logout</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </nav>
</header>